In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [8]:
dep=dataset[['classification_yes']]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split( indep, dep, test_size=0.30, random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(x_train)
X_test=sc.transform(x_test)

In [11]:
from sklearn.linear_model import LogisticRegression

In [12]:
from sklearn.model_selection import GridSearchCV
param_grid = {'solver':['newton-cg','lbfgs','liblinear','saga'],
             'penalty':['l2']}
grid = GridSearchCV(LogisticRegression(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'penalty': ['l2'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'saga']},
             scoring='f1_weighted', verbose=3)

In [13]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [30]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("the f1_macro value for best parameter{}:".format(grid.best_params_),f1_macro)

the f1_macro value for best parameter{'penalty': 'l2', 'solver': 'newton-cg'}: 0.9916844900066377

In [15]:
print("the confusion matrix:\n",cm)

the confusion matrix:
 [[45  0]
 [ 1 74]]

In [16]:
print("the report:\n",clf_report)

the report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        45
           1       1.00      0.99      0.99        75

    accuracy                           0.99       120
   macro avg       0.99      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120

In [17]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

1.0

In [18]:
table=pd.DataFrame.from_dict(re)

In [19]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_penalty,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.053294,0.036539,0.017192,0.008332,l2,newton-cg,"{'penalty': 'l2', 'solver': 'newton-cg'}",0.982221,1.000000,0.982221,1.000000,1.000000,0.992888,0.008710,1
1,0.095480,0.078686,0.020031,0.013825,l2,lbfgs,"{'penalty': 'l2', 'solver': 'lbfgs'}",0.982221,1.000000,0.982221,1.000000,1.000000,0.992888,0.008710,1
2,0.036327,0.017629,0.033485,0.010822,l2,liblinear,"{'penalty': 'l2', 'solver': 'liblinear'}",0.964572,0.982221,0.964572,0.964572,0.981894,0.971566,0.008567,4
3,0.059471,0.038640,0.020634,0.007099,l2,saga,"{'penalty': 'l2', 'solver': 'saga'}",0.982221,0.982221,0.964572,0.982221,0.981894,0.978626,0.007028,3

In [28]:
age=float(input("enter the age:"))
bp=float(input("enter the bp:"))
al=float(input("enter the al:"))
su=float(input("enter the su:"))
bgr=float(input("enter the bgr:"))
bu=float(input("enter the bu:"))
sc=float(input("enter the sc:"))
sod=float(input("enter the sod:"))
pot=float(input("enter the pot:"))
hrmo=float(input("enter the hrmo:"))
pcv=float(input("enter the pcv:"))
wc=float(input("enter the wc:"))
rc=float(input("enter the rc:"))
sg_b=int(input("sg_b 0 or 1:"))
sg_c=int(input("sg_c 0 or 1:"))
sg_d=int(input("sg_d 0 or 1:"))
sg_e=int(input("sg_e 0 or 1:"))
rbc_normal=int(input("rbc_normal 0 or 1:"))
pc_normal=int(input("pc_normal 0 or 1:"))
pcc_present=int(input("pcc_present 0 or 1:"))
ba_present=int(input("ba_present 0 or 1:"))
htn_yes=int(input("htn_yes 0 or 1:"))
dm_yes=int(input("dm_yes 0 or 1:"))
cad_yes=int(input("cad_yes 0 or 1:"))
appet_yes=int(input("appet_yes 0 or 1:"))
pe_yes=int(input("pe_yes 0 or 1:"))
ane_yes=int(input("ane_yes 0 or 1:"))

enter the age: 34
enter the bp: 64646
enter the al: 0457
enter the su: 6089
enter the bgr: 43
enter the bu: 70
enter the sc: 8375
enter the sod: 97067
enter the pot: 385
enter the hrmo: 0896
enter the pcv: 235
enter the wc: 5738
enter the rc: 705
sg_b 0 or 1: 1
sg_c 0 or 1: 0
sg_d 0 or 1: 0
sg_e 0 or 1: 0
rbc_normal 0 or 1: 1
pc_normal 0 or 1: 0
pcc_present 0 or 1: 1
ba_present 0 or 1: 1
htn_yes 0 or 1: 1
dm_yes 0 or 1: 0
cad_yes 0 or 1: 1
appet_yes 0 or 1: 0
pe_yes 0 or 1: 1
ane_yes 0 or 1: 1

In [29]:
future_predictions=grid.predict([[age, bp, al, su, bgr, bu, sc, sod, pot, hrmo, pcv,wc, rc, sg_b, sg_c, sg_d, sg_e, rbc_normal, pc_normal,
       pcc_present, ba_present, htn_yes, dm_yes, cad_yes,
       appet_yes, pe_yes, ane_yes]])
print("future_predictions={}".format(future_predictions))

future_predictions=[1]

In [31]:
import pickle

In [32]:
filename="finalized_model_LogisticReg.sav"

In [37]:
pickle.dump(grid,open(filename,"wb"))

In [38]:
loaded_model=pickle.load(open("finalized_model_LogisticReg.sav","rb"))

In [40]:
result=loaded_model.predict([[12,8742,233,1,3298,2490,424790,892.942,90,73,74,1028.372382,1931,1,1,0,1,1,0,0,1,1,1,0,1,0,1]])
result

array([1])