In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [8]:
dep=dataset[['classification_yes']]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split( indep, dep, test_size=0.30, random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(x_train)
X_test=sc.transform(x_test)

In [11]:
from sklearn.tree import DecisionTreeClassifier

In [13]:
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['gini','entropy','log_loss'],'max_features': ['None','sqrt','log2'],'splitter':['best','random']}
grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning:
30 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 889, in fit
    super().fit(
  File "C:\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2', 'auto' (deprecated)} or None. Got 'None' instead.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 889, in fit
    super().fit(
  File "C:\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'auto' (deprecated), 'sqrt', 'log2'} or None. Got 'None' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:952: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.93202325 0.96433557 0.96438283 0.93586264
        nan        nan 0.95359804 0.94999604 0.94642014 0.97157446
        nan        nan 0.93585372 0.96439471 0.93502107 0.9748624 ]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['None', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [14]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [15]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("the f1_macro value for best parameter{}:".format(grid.best_params_),f1_macro)

the f1_macro value for best parameter{'criterion': 'log_loss', 'max_features': 'log2', 'splitter': 'random'}: 0.975053470019913

In [16]:
print("the confusion matrix:\n",cm)

the confusion matrix:
 [[44  1]
 [ 2 73]]

In [17]:
print("the report:\n",clf_report)

the report:
               precision    recall  f1-score   support

           0       0.96      0.98      0.97        45
           1       0.99      0.97      0.98        75

    accuracy                           0.97       120
   macro avg       0.97      0.98      0.97       120
weighted avg       0.98      0.97      0.98       120

In [18]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9755555555555556

In [19]:
table=pd.DataFrame.from_dict(re)

In [20]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.009329,0.007617,0.000000,0.000000,gini,None,best,"{'criterion': 'gini', 'max_features': 'None', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
1,0.009375,0.007654,0.000000,0.000000,gini,None,random,"{'criterion': 'gini', 'max_features': 'None', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
2,0.027435,0.031030,0.024964,0.007617,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.964572,0.946663,0.912029,0.891667,0.945185,0.932023,0.026364,12
3,0.008790,0.006072,0.025270,0.006243,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.982051,0.964572,0.946663,0.946663,0.981728,0.964336,0.015754,5
4,0.010529,0.000834,0.020227,0.000020,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.964286,0.964572,0.929144,0.963912,0.964383,0.022408,4
5,0.006492,0.004694,0.021911,0.003523,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.929144,0.964286,0.893717,0.946153,0.946014,0.935863,0.023825,9
6,0.001228,0.001003,0.000000,0.000000,entropy,None,best,"{'criterion': 'entropy', 'max_features': 'None...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
7,0.003670,0.004552,0.000000,0.000000,entropy,None,random,"{'criterion': 'entropy', 'max_features': 'None...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
8,0.007680,0.003922,0.021040,0.006456,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.947015,0.911105,0.964572,0.982051,0.963247,0.953598,0.023967,6
9,0.007267,0.003747,0.019034,0.003524,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.982221,0.929144,0.964286,0.929144,0.945185,0.949996,0.020666,7
10,0.004047,0.004235,0.020226,0.000016,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.947015,0.946153,0.929144,0.946153,0.963636,0.946420,0.010912,8
11,0.004452,0.004675,0.022453,0.006697,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.982221,0.929144,0.964286,0.982221,1.000000,0.971574,0.024034,2
12,0.000000,0.000000,0.000000,0.000000,log_loss,None,best,"{'criterion': 'log_loss', 'max_features': 'Non...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.005235,0.004331,0.000000,0.000000,log_loss,None,random,"{'criterion': 'log_loss', 'max_features': 'Non...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
14,0.001615,0.003229,0.025071,0.008187,log_loss,sqrt,best,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.911105,0.964286,0.912029,0.946663,0.945185,0.935854,0.020940,10
15,0.004471,0.004687,0.020262,0.000026,log_loss,sqrt,random,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.982221,0.946663,0.982051,0.929144,0.981894,0.964395,0.022328,3
16,0.009609,0.004339,0.019976,0.000553,log_loss,log2,best,"{'criterion': 'log_loss', 'max_features': 'log...",0.964572,0.928571,0.946663,0.890114,0.945185,0.935021,0.025181,11
17,0.006059,0.004226,0.018642,0.004340,log_loss,log2,random,"{'criterion': 'log_loss', 'max_features': 'log...",0.982221,0.982221,0.964572,0.982051,0.963247,0.974862,0.008953,1