In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [8]:
dep=dataset[['classification_yes']]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split( indep, dep, test_size=0.30, random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(x_train)
X_test=sc.transform(x_test)

In [11]:
from sklearn.ensemble import RandomForestClassifier

In [12]:
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['gini','entropy','log_loss'],'max_features': ['None','sqrt','log2'],'class_weight':['balanced','balanced_subsample','None']}
grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,y_train)

Fitting 5 folds for each of 27 candidates, totalling 135 fits

C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning:
75 fits failed out of a total of 135.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\anaconda3\Lib\site-packages\sklearn\ensemble\_forest.py", line 340, in fit
    self._validate_params()
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2', 'auto' (deprecated)} or None. Got 'None' instead.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\anaconda3\Lib\site-packages\sklearn\ensemble\_forest.py", line 340, in fit
    self._validate_params()
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'auto' (deprecated), 'sqrt', 'log2'} or None. Got 'None' instead.

--------------------------------------------------------------------------------
45 fits failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\anaconda3\Lib\site-packages\sklearn\ensemble\_forest.py", line 340, in fit
    self._validate_params()
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'class_weight' parameter of RandomForestClassifier must be a str among {'balanced', 'balanced_subsample'}, an instance of 'dict', an instance of 'list' or None. Got 'None' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:952: UserWarning: One or more of the test scores are non-finite: [       nan 0.98194817 0.98210238        nan 0.96785343 0.98926456
        nan 0.97135391 0.98194817        nan 0.97135391 0.97490694
        nan 0.97859093 0.97490694        nan 0.97503791 0.97859093
        nan        nan        nan        nan        nan        nan
        nan        nan        nan]
  warnings.warn(
C:\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:909: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'class_weight': ['balanced', 'balanced_subsample',
                                          'None'],
                         'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['None', 'sqrt', 'log2']},
             scoring='f1_weighted', verbose=3)

In [13]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [14]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("the f1_macro value for best parameter{}:".format(grid.best_params_),f1_macro)

the f1_macro value for best parameter{'class_weight': 'balanced', 'criterion': 'entropy', 'max_features': 'log2'}: 0.9916474440062505

In [15]:
print("the confusion matrix:\n",cm)

the confusion matrix:
 [[44  1]
 [ 0 75]]

In [16]:
print("the report:\n",clf_report)

the report:
               precision    recall  f1-score   support

           0       1.00      0.98      0.99        45
           1       0.99      1.00      0.99        75

    accuracy                           0.99       120
   macro avg       0.99      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120

In [17]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

1.0

In [18]:
table=pd.DataFrame.from_dict(re)

In [19]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_class_weight,param_criterion,param_max_features,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003126,0.006252,0.000000,0.000000,balanced,gini,None,"{'class_weight': 'balanced', 'criterion': 'gin...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
1,0.484188,0.010204,0.043328,0.003735,balanced,gini,sqrt,"{'class_weight': 'balanced', 'criterion': 'gin...",1.0,0.945469,0.982221,0.982051,1.0,0.981948,0.019913,3
2,0.467377,0.011393,0.051387,0.011861,balanced,gini,log2,"{'class_weight': 'balanced', 'criterion': 'gin...",1.0,0.963889,0.964572,0.982051,1.0,0.982102,0.015998,2
3,0.000416,0.000833,0.000000,0.000000,balanced,entropy,None,"{'class_weight': 'balanced', 'criterion': 'ent...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
4,0.470029,0.010009,0.042076,0.003222,balanced,entropy,sqrt,"{'class_weight': 'balanced', 'criterion': 'ent...",1.0,0.945469,0.929513,0.964286,1.0,0.967853,0.028463,12
5,0.487010,0.037197,0.044155,0.004557,balanced,entropy,log2,"{'class_weight': 'balanced', 'criterion': 'ent...",1.0,0.982051,0.982221,0.982051,1.0,0.989265,0.008766,1
6,0.002017,0.004033,0.000000,0.000000,balanced,log_loss,None,"{'class_weight': 'balanced', 'criterion': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
7,0.473676,0.006694,0.044950,0.004701,balanced,log_loss,sqrt,"{'class_weight': 'balanced', 'criterion': 'log...",1.0,0.945469,0.947015,0.964286,1.0,0.971354,0.024305,10
8,0.469661,0.010164,0.047755,0.003756,balanced,log_loss,log2,"{'class_weight': 'balanced', 'criterion': 'log...",1.0,0.945469,0.982221,0.982051,1.0,0.981948,0.019913,3
9,0.000000,0.000000,0.000000,0.000000,balanced_subsample,gini,None,"{'class_weight': 'balanced_subsample', 'criter...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
10,0.567116,0.016649,0.046117,0.005503,balanced_subsample,gini,sqrt,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.945469,0.947015,0.964286,1.0,0.971354,0.024305,10
11,0.458276,0.034447,0.032280,0.004010,balanced_subsample,gini,log2,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.945469,0.947015,0.982051,1.0,0.974907,0.024310,8
12,0.007241,0.003732,0.000000,0.000000,balanced_subsample,entropy,None,"{'class_weight': 'balanced_subsample', 'criter...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.441461,0.003846,0.032683,0.002966,balanced_subsample,entropy,sqrt,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.963889,0.947015,0.982051,1.0,0.978591,0.020697,5
14,0.437304,0.005341,0.036707,0.003687,balanced_subsample,entropy,log2,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.945469,0.947015,0.982051,1.0,0.974907,0.024310,8
15,0.000000,0.000000,0.000000,0.000000,balanced_subsample,log_loss,None,"{'class_weight': 'balanced_subsample', 'criter...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
16,0.450726,0.037195,0.040357,0.011074,balanced_subsample,log_loss,sqrt,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.963889,0.947015,0.964286,1.0,0.975038,0.021314,7
17,0.530777,0.022670,0.050042,0.015637,balanced_subsample,log_loss,log2,"{'class_weight': 'balanced_subsample', 'criter...",1.0,0.963889,0.947015,0.982051,1.0,0.978591,0.020697,5
18,0.002021,0.003122,0.000000,0.000000,None,gini,None,"{'class_weight': 'None', 'criterion': 'gini', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
19,0.002017,0.004033,0.000000,0.000000,None,gini,sqrt,"{'class_weight': 'None', 'criterion': 'gini', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
20,0.000409,0.000817,0.000000,0.000000,None,gini,log2,"{'class_weight': 'None', 'criterion': 'gini', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
21,0.003627,0.004488,0.000000,0.000000,None,entropy,None,"{'class_weight': 'None', 'criterion': 'entropy...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
22,0.002425,0.003912,0.000000,0.000000,None,entropy,sqrt,"{'class_weight': 'None', 'criterion': 'entropy...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
23,0.003212,0.003934,0.000000,0.000000,None,entropy,log2,"{'class_weight': 'None', 'criterion': 'entropy...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
24,0.001612,0.003224,0.000000,0.000000,None,log_loss,None,"{'class_weight': 'None', 'criterion': 'log_los...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
25,0.000819,0.001003,0.000000,0.000000,None,log_loss,sqrt,"{'class_weight': 'None', 'criterion': 'log_los...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
26,0.001611,0.003222,0.000000,0.000000,None,log_loss,log2,"{'class_weight': 'None', 'criterion': 'log_los...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13