In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [8]:
dep=dataset[['classification_yes']]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split( indep, dep, test_size=0.30, random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(x_train)
X_test=sc.transform(x_test)

In [11]:
from sklearn.neighbors import KNeighborsClassifier

In [12]:
from sklearn.model_selection import GridSearchCV
param_grid = {'metric':['minkowski','callable'],'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute'],'weights':['uniform','distance']}
grid = GridSearchCV(KNeighborsClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning:
40 fits failed out of a total of 80.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
24 fits failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 213, in fit
    self._validate_params()
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'metric' parameter of KNeighborsClassifier must be a str among {'l1', 'pyfunc', 'minkowski', 'yule', 'jaccard', 'chebyshev', 'cosine', 'wminkowski', 'canberra', 'braycurtis', 'seuclidean', 'infinity', 'haversine', 'dice', 'cityblock', 'nan_euclidean', 'l2', 'sokalmichener', 'precomputed', 'sqeuclidean', 'mahalanobis', 'manhattan', 'rogerstanimoto', 'hamming', 'russellrao', 'sokalsneath', 'correlation', 'matching', 'p', 'euclidean', 'kulsinski'} or a callable. Got 'callable' instead.

--------------------------------------------------------------------------------
16 fits failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 213, in fit
    self._validate_params()
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'metric' parameter of KNeighborsClassifier must be a str among {'yule', 'pyfunc', 'dice', 'haversine', 'l1', 'minkowski', 'canberra', 'kulsinski', 'russellrao', 'cosine', 'precomputed', 'p', 'nan_euclidean', 'rogerstanimoto', 'cityblock', 'euclidean', 'chebyshev', 'sokalsneath', 'jaccard', 'hamming', 'braycurtis', 'correlation', 'mahalanobis', 'l2', 'sokalmichener', 'sqeuclidean', 'infinity', 'manhattan', 'matching', 'wminkowski', 'seuclidean'} or a callable. Got 'callable' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.95742819 0.96095797        nan        nan 0.95742819 0.96095797
        nan        nan 0.95742819 0.96095797        nan        nan
 0.95742819 0.96095797        nan        nan]
  warnings.warn(
C:\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'metric': ['minkowski', 'callable'],
                         'weights': ['uniform', 'distance']},
             scoring='f1_weighted', verbose=3)

In [13]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [14]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("the f1_macro value for best parameter{}:".format(grid.best_params_),f1_macro)

the f1_macro value for best parameter{'algorithm': 'auto', 'metric': 'minkowski', 'weights': 'distance'}: 0.9505208333333334

In [15]:
print("the confusion matrix:\n",cm)

the confusion matrix:
 [[45  0]
 [ 6 69]]

In [16]:
print("the report:\n",clf_report)

the report:
               precision    recall  f1-score   support

           0       0.88      1.00      0.94        45
           1       1.00      0.92      0.96        75

    accuracy                           0.95       120
   macro avg       0.94      0.96      0.95       120
weighted avg       0.96      0.95      0.95       120

In [17]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

1.0

In [18]:
table=pd.DataFrame.from_dict(re)

In [19]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_metric,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.484431,0.580594,0.960629,1.087330,auto,minkowski,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.964572,0.964572,0.929513,0.964572,0.963912,0.957428,0.01396,5
1,0.009369,0.007650,0.078133,0.009883,auto,minkowski,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.964572,0.982221,0.929513,0.964572,0.963912,0.960958,0.01718,1
2,0.003126,0.006253,0.000000,0.000000,auto,callable,uniform,"{'algorithm': 'auto', 'metric': 'callable', 'w...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
3,0.006250,0.007654,0.000000,0.000000,auto,callable,distance,"{'algorithm': 'auto', 'metric': 'callable', 'w...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
4,0.012500,0.011693,0.037503,0.007651,ball_tree,minkowski,uniform,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.964572,0.964572,0.929513,0.964572,0.963912,0.957428,0.01396,5
5,0.012499,0.011692,0.031257,0.009883,ball_tree,minkowski,distance,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.964572,0.982221,0.929513,0.964572,0.963912,0.960958,0.01718,1
6,0.000000,0.000000,0.000000,0.000000,ball_tree,callable,uniform,"{'algorithm': 'ball_tree', 'metric': 'callable...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.000000,0.000000,0.000000,0.000000,ball_tree,callable,distance,"{'algorithm': 'ball_tree', 'metric': 'callable...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.031250,0.019764,0.046882,0.019770,kd_tree,minkowski,uniform,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.964572,0.964572,0.929513,0.964572,0.963912,0.957428,0.01396,5
9,0.012498,0.006249,0.025005,0.007656,kd_tree,minkowski,distance,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.964572,0.982221,0.929513,0.964572,0.963912,0.960958,0.01718,1
10,0.006254,0.007660,0.000000,0.000000,kd_tree,callable,uniform,"{'algorithm': 'kd_tree', 'metric': 'callable',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
11,0.000000,0.000000,0.000000,0.000000,kd_tree,callable,distance,"{'algorithm': 'kd_tree', 'metric': 'callable',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
12,0.003125,0.006250,0.075004,0.018227,brute,minkowski,uniform,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.964572,0.964572,0.929513,0.964572,0.963912,0.957428,0.01396,5
13,0.003125,0.006250,0.058200,0.009906,brute,minkowski,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.964572,0.982221,0.929513,0.964572,0.963912,0.960958,0.01718,1
14,0.003126,0.006252,0.000000,0.000000,brute,callable,uniform,"{'algorithm': 'brute', 'metric': 'callable', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
15,0.003126,0.006252,0.000000,0.000000,brute,callable,distance,"{'algorithm': 'brute', 'metric': 'callable', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9